@extends('layouts.app')

@section('title', 'Report Details')

@section('content')
    <x-ui.panel tone="surface" class="p-6 md:p-8">
        <x-ui.page-header
            eyebrow="Report details"
            title="{{ $report->report_type }}"
            description="Review the generated data, track report status, and export the regulatory snapshot."
        >
            <x-slot:actions>
                <a class="inline-flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/10" href="{{ route('admin.reports.download', $report) }}">
                    Download JSON
                </a>
            </x-slot:actions>
        </x-ui.page-header>

        <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-[28px] border border-white/10 bg-slate-950/60 p-5">
                <p class="text-xs uppercase tracking-[0.35em] text-slate-500">Status</p>
                <p class="mt-2 text-lg font-semibold text-white">{{ $report->statusValue() }}</p>
            </div>
            <div class="rounded-[28px] border border-white/10 bg-slate-950/60 p-5">
                <p class="text-xs uppercase tracking-[0.35em] text-slate-500">Period</p>
                <p class="mt-2 text-lg font-semibold text-white">{{ optional($report->date_range_start)->format('Y-m-d') }} to {{ optional($report->date_range_end)->format('Y-m-d') }}</p>
            </div>
            <div class="rounded-[28px] border border-white/10 bg-slate-950/60 p-5">
                <p class="text-xs uppercase tracking-[0.35em] text-slate-500">Generated by</p>
                <p class="mt-2 text-lg font-semibold text-white">{{ $report->author?->name ?? 'System' }}</p>
            </div>
            <div class="rounded-[28px] border border-white/10 bg-slate-950/60 p-5">
                <p class="text-xs uppercase tracking-[0.35em] text-slate-500">Applications</p>
                <p class="mt-2 text-lg font-semibold text-white">{{ data_get($report->aggregated_data, 'total_applications', 0) }}</p>
            </div>
        </div>

        <div class="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
            <div class="space-y-6">
                <x-ui.panel tone="inset" class="p-5 md:p-6">
                    <p class="text-xs font-semibold uppercase tracking-[0.35em] text-cyan-300/70">Summary</p>
                    <div class="mt-4 grid gap-3 sm:grid-cols-2">
                        <div class="rounded-2xl border border-white/10 bg-white/5 p-4">
                            <p class="text-[10px] uppercase tracking-[0.3em] text-slate-500">Jobs posted</p>
                            <p class="mt-2 text-2xl font-semibold text-white">{{ data_get($report->aggregated_data, 'total_jobs_posted', 0) }}</p>
                        </div>
                        <div class="rounded-2xl border border-white/10 bg-white/5 p-4">
                            <p class="text-[10px] uppercase tracking-[0.3em] text-slate-500">Applications</p>
                            <p class="mt-2 text-2xl font-semibold text-white">{{ data_get($report->aggregated_data, 'total_applications', 0) }}</p>
                        </div>
                        <div class="rounded-2xl border border-white/10 bg-white/5 p-4">
                            <p class="text-[10px] uppercase tracking-[0.3em] text-slate-500">Avg salary min</p>
                            <p class="mt-2 text-2xl font-semibold text-white">UGX {{ number_format((float) data_get($report->aggregated_data, 'average_salary_min', 0)) }}</p>
                        </div>
                        <div class="rounded-2xl border border-white/10 bg-white/5 p-4">
                            <p class="text-[10px] uppercase tracking-[0.3em] text-slate-500">Avg salary max</p>
                            <p class="mt-2 text-2xl font-semibold text-white">UGX {{ number_format((float) data_get($report->aggregated_data, 'average_salary_max', 0)) }}</p>
                        </div>
                    </div>
                </x-ui.panel>

                <x-ui.panel tone="inset" class="p-5 md:p-6">
                    <p class="text-xs font-semibold uppercase tracking-[0.35em] text-cyan-300/70">Distribution</p>
                    <div class="mt-4 grid gap-4 md:grid-cols-2">
                        <div>
                            <p class="text-xs uppercase tracking-[0.3em] text-slate-500">Jobs by type</p>
                            <div class="mt-3 flex flex-wrap gap-2">
                                @forelse((array) data_get($report->aggregated_data, 'jobs_by_type', []) as $type => $count)
                                    <span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold uppercase tracking-[0.25em] text-slate-200">{{ $type }}: {{ $count }}</span>
                                @empty
                                    <span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">No data</span>
                                @endforelse
                            </div>
                        </div>
                        <div>
                            <p class="text-xs uppercase tracking-[0.3em] text-slate-500">Applications by status</p>
                            <div class="mt-3 flex flex-wrap gap-2">
                                @forelse((array) data_get($report->aggregated_data, 'applications_by_status', []) as $status => $count)
                                    <span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold uppercase tracking-[0.25em] text-slate-200">{{ $status }}: {{ $count }}</span>
                                @empty
                                    <span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">No data</span>
                                @endforelse
                            </div>
                        </div>
                    </div>
                </x-ui.panel>
            </div>

            <div class="space-y-6">
                <x-ui.panel tone="inset" class="p-5 md:p-6">
                    <p class="text-xs font-semibold uppercase tracking-[0.35em] text-cyan-300/70">Conversion</p>
                    <p class="mt-3 text-4xl font-semibold text-white">{{ data_get($report->aggregated_data, 'application_to_hire_conversion_rate', 0) }}%</p>
                    <p class="mt-3 text-sm leading-7 text-slate-400">Share of applications that converted to hires during the selected reporting period.</p>
                </x-ui.panel>

                <x-ui.panel tone="inset" class="p-5 md:p-6">
                    <p class="text-xs font-semibold uppercase tracking-[0.35em] text-cyan-300/70">Top jobs</p>
                    <div class="mt-4 space-y-3">
                        @forelse(data_get($report->aggregated_data, 'top_job_titles', []) as $title)
                            <div class="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200">{{ $title }}</div>
                        @empty
                            <div class="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-400">No top jobs recorded.</div>
                        @endforelse
                    </div>
                </x-ui.panel>
            </div>
        </div>

        <details class="mt-8 rounded-[28px] border border-white/10 bg-slate-950/70 p-5">
            <summary class="cursor-pointer list-none text-sm font-semibold uppercase tracking-[0.3em] text-slate-300">
                Raw report data
            </summary>
            <pre class="mt-5 overflow-auto rounded-2xl border border-white/10 bg-slate-950/80 p-5 text-sm text-slate-200">{{ json_encode($report->aggregated_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
        </details>
    </x-ui.panel>
@endsection
