@extends('layouts.admin')

@section('title', 'Report Details')

@section('content')
<div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-3 md:p-6">
    <!-- Header -->
    <div class="mb-6">
        <div class="flex items-center justify-between gap-4">
            <div>
                <h1 class="text-3xl font-bold text-gray-900">{{ $report->report_type }}</h1>
                <p class="text-gray-600 mt-1">Review the generated data, track report status, and export the regulatory snapshot.</p>
            </div>
            <a href="{{ route('admin.reports.download', $report) }}" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-semibold">
                <i class="fas fa-download mr-2"></i>Download JSON
            </a>
        </div>
    </div>

    <!-- Status Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-xs text-gray-600 font-semibold uppercase">Status</p>
            <p class="text-2xl font-bold text-gray-900 mt-2">
                <span class="px-3 py-1 text-xs font-semibold rounded-full
                    @if($report->statusValue() === 'draft') bg-yellow-100 text-yellow-800
                    @elseif($report->statusValue() === 'submitted') bg-green-100 text-green-800
                    @else bg-blue-100 text-blue-800
                    @endif">
                    {{ ucfirst($report->statusValue()) }}
                </span>
            </p>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-xs text-gray-600 font-semibold uppercase">Period</p>
            <p class="text-lg font-bold text-gray-900 mt-2">
                {{ optional($report->date_range_start)->format('M d, Y') }} to {{ optional($report->date_range_end)->format('M d, Y') }}
            </p>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-xs text-gray-600 font-semibold uppercase">Generated by</p>
            <p class="text-lg font-bold text-gray-900 mt-2">{{ $report->author?->name ?? 'System' }}</p>
        </div>

        <div class="bg-white rounded-lg shadow p-6">
            <p class="text-xs text-gray-600 font-semibold uppercase">Applications</p>
            <p class="text-lg font-bold text-gray-900 mt-2">{{ data_get($report->aggregated_data, 'total_applications', 0) }}</p>
        </div>
    </div>

    <!-- Main Content Grid -->
    <div class="grid gap-6 lg:grid-cols-3">
        <div class="lg:col-span-2 space-y-6">
            <!-- Summary -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h2 class="text-lg font-bold text-gray-900 mb-4">
                    <i class="fas fa-chart-bar text-red-600 mr-2"></i>Summary
                </h2>
                <div class="grid grid-cols-2 gap-4">
                    <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
                        <p class="text-xs text-gray-600 font-semibold uppercase">Jobs Posted</p>
                        <p class="text-2xl font-bold text-gray-900 mt-2">{{ data_get($report->aggregated_data, 'total_jobs_posted', 0) }}</p>
                    </div>
                    <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
                        <p class="text-xs text-gray-600 font-semibold uppercase">Applications</p>
                        <p class="text-2xl font-bold text-gray-900 mt-2">{{ data_get($report->aggregated_data, 'total_applications', 0) }}</p>
                    </div>
                    <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
                        <p class="text-xs text-gray-600 font-semibold uppercase">Avg Salary Min</p>
                        <p class="text-2xl font-bold text-gray-900 mt-2">UGX {{ number_format((float) data_get($report->aggregated_data, 'average_salary_min', 0)) }}</p>
                    </div>
                    <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
                        <p class="text-xs text-gray-600 font-semibold uppercase">Avg Salary Max</p>
                        <p class="text-2xl font-bold text-gray-900 mt-2">UGX {{ number_format((float) data_get($report->aggregated_data, 'average_salary_max', 0)) }}</p>
                    </div>
                </div>
            </div>

            <!-- Distribution -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h2 class="text-lg font-bold text-gray-900 mb-4">
                    <i class="fas fa-pie-chart text-orange-600 mr-2"></i>Distribution
                </h2>
                <div class="grid grid-cols-2 gap-6">
                    <div>
                        <p class="text-sm font-semibold text-gray-700 mb-3">Jobs by Type</p>
                        <div class="space-y-2">
                            @forelse((array) data_get($report->aggregated_data, 'jobs_by_type', []) as $type => $count)
                                <div class="flex items-center justify-between p-2 bg-gray-50 rounded border border-gray-200">
                                    <span class="text-sm text-gray-700">{{ $type }}</span>
                                    <span class="px-2 py-1 text-xs font-semibold bg-blue-100 text-blue-800 rounded">{{ $count }}</span>
                                </div>
                            @empty
                                <p class="text-sm text-gray-500">No data available</p>
                            @endforelse
                        </div>
                    </div>
                    <div>
                        <p class="text-sm font-semibold text-gray-700 mb-3">Applications by Status</p>
                        <div class="space-y-2">
                            @forelse((array) data_get($report->aggregated_data, 'applications_by_status', []) as $status => $count)
                                <div class="flex items-center justify-between p-2 bg-gray-50 rounded border border-gray-200">
                                    <span class="text-sm text-gray-700">{{ ucfirst($status) }}</span>
                                    <span class="px-2 py-1 text-xs font-semibold bg-green-100 text-green-800 rounded">{{ $count }}</span>
                                </div>
                            @empty
                                <p class="text-sm text-gray-500">No data available</p>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>

            <!-- Raw Data -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <details class="cursor-pointer">
                    <summary class="text-lg font-bold text-gray-900 flex items-center">
                        <i class="fas fa-code text-purple-600 mr-2"></i>Raw Report Data
                    </summary>
                    <pre class="mt-4 overflow-auto bg-gray-900 text-gray-100 p-4 rounded-lg text-sm">{{ json_encode($report->aggregated_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
                </details>
            </div>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
            <!-- Conversion Rate -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-4">
                    <i class="fas fa-chart-line text-green-600 mr-2"></i>Conversion Rate
                </h3>
                <p class="text-4xl font-bold text-green-600">{{ data_get($report->aggregated_data, 'application_to_hire_conversion_rate', 0) }}%</p>
                <p class="text-sm text-gray-600 mt-3">Share of applications that converted to hires during the selected reporting period.</p>
            </div>

            <!-- Top Jobs -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-4">
                    <i class="fas fa-briefcase text-blue-600 mr-2"></i>Top Jobs
                </h3>
                <div class="space-y-2">
                    @forelse(data_get($report->aggregated_data, 'top_job_titles', []) as $title)
                        <div class="p-3 bg-blue-50 rounded-lg border border-blue-200 text-sm text-gray-700">
                            {{ $title }}
                        </div>
                    @empty
                        <p class="text-sm text-gray-500">No top jobs recorded.</p>
                    @endforelse
                </div>
            </div>

            <!-- Report Info -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-4">
                    <i class="fas fa-info-circle text-gray-600 mr-2"></i>Report Info
                </h3>
                <div class="space-y-3">
                    <div>
                        <p class="text-xs text-gray-600 font-semibold uppercase">Created</p>
                        <p class="text-gray-900 font-semibold mt-1">{{ $report->created_at->format('M d, Y \a\t h:i A') }}</p>
                    </div>
                    <div>
                        <p class="text-xs text-gray-600 font-semibold uppercase">Last Updated</p>
                        <p class="text-gray-900 font-semibold mt-1">{{ $report->updated_at->format('M d, Y \a\t h:i A') }}</p>
                    </div>
                    @if($report->notes)
                    <div>
                        <p class="text-xs text-gray-600 font-semibold uppercase">Notes</p>
                        <p class="text-gray-900 mt-1">{{ $report->notes }}</p>
                    </div>
                    @endif
                </div>
            </div>

            <!-- Actions -->
            <div class="bg-white rounded-xl shadow-lg p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-4">Actions</h3>
                <div class="space-y-2">
                    <a href="{{ route('admin.reports.index') }}" class="block w-full px-4 py-2 text-center bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition font-semibold text-sm">
                        <i class="fas fa-arrow-left mr-2"></i>Back to Reports
                    </a>
                    <a href="{{ route('admin.reports.download', $report) }}" class="block w-full px-4 py-2 text-center bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-semibold text-sm">
                        <i class="fas fa-download mr-2"></i>Download JSON
                    </a>
                    @if($report->statusValue() === 'draft')
                    <form method="post" action="{{ route('admin.reports.submit', $report) }}" class="w-full">
                        @csrf
                        @method('patch')
                        <button type="submit" class="w-full px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition font-semibold text-sm">
                            <i class="fas fa-check mr-2"></i>Submit Report
                        </button>
                    </form>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
